// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC60E7eRlv9BScLzomj6pXnx_J60e9IWSY',
    appId: '1:77459484449:web:b82d30ab5b690e85821860',
    messagingSenderId: '77459484449',
    projectId: 'bank-app-722aa',
    authDomain: 'bank-app-722aa.firebaseapp.com',
    storageBucket: 'bank-app-722aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvoN1xA4nhEegAFau6P5wTkJu274Eh0to',
    appId: '1:77459484449:android:3f37f1f2028f204a821860',
    messagingSenderId: '77459484449',
    projectId: 'bank-app-722aa',
    storageBucket: 'bank-app-722aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfcQEbmr4QuNW6IHaJ9MI9Gs5Tyj-bxSg',
    appId: '1:77459484449:ios:b2898355d51b536a821860',
    messagingSenderId: '77459484449',
    projectId: 'bank-app-722aa',
    storageBucket: 'bank-app-722aa.firebasestorage.app',
    iosBundleId: 'com.example.flutterBankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfcQEbmr4QuNW6IHaJ9MI9Gs5Tyj-bxSg',
    appId: '1:77459484449:ios:b2898355d51b536a821860',
    messagingSenderId: '77459484449',
    projectId: 'bank-app-722aa',
    storageBucket: 'bank-app-722aa.firebasestorage.app',
    iosBundleId: 'com.example.flutterBankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC60E7eRlv9BScLzomj6pXnx_J60e9IWSY',
    appId: '1:77459484449:web:45e9ce97dfcff3bc821860',
    messagingSenderId: '77459484449',
    projectId: 'bank-app-722aa',
    authDomain: 'bank-app-722aa.firebaseapp.com',
    storageBucket: 'bank-app-722aa.firebasestorage.app',
  );

}