# Form implementation generated from reading ui file 'C:\Users\andre\OneDrive\Escritorio\Clase\2 DAM\Programacion Multimedia\Git_Hub\ProyectoFinal_Andreu\Datafono Python\Datafono.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(529, 577)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(120, 10, 331, 61))
        self.label.setObjectName("label")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=Form)
        self.lcdNumber.setGeometry(QtCore.QRect(170, 160, 211, 51))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(150, 70, 241, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(110, 210, 331, 361))
        self.widget.setObjectName("widget")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 110, 75, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(130, 190, 75, 71))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(40, 30, 75, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 110, 75, 71))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 30, 75, 71))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 190, 75, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 30, 75, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 190, 75, 71))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 280, 75, 41))
        self.pushButton_10.setText("")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::ApplicationExit")
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setStyleSheet("background-color: red;")

        self.pushButton_12 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_12.setGeometry(QtCore.QRect(220, 280, 75, 41))
        self.pushButton_12.setText("")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::MailSend")
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.setStyleSheet("background-color: green;")
        
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 110, 75, 71))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 270, 75, 61))
        self.pushButton_11.setObjectName("pushButton_11")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt; text-decoration: underline;\">Introduce la tarjeta a la que se le hara el cobro</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Form", "4"))
        self.pushButton_7.setText(_translate("Form", "8"))
        self.pushButton.setText(_translate("Form", "1"))
        self.pushButton_8.setText(_translate("Form", "6"))
        self.pushButton_6.setText(_translate("Form", "3"))
        self.pushButton_4.setText(_translate("Form", "7"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_11.setText(_translate("Form", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
