name: flutter_bank_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  get_it: ^8.0.2
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  rive: ^0.13.20
  shared_preferences: ^2.3.3
  rxdart: ^0.28.0
  carousel_slider: ^5.0.0
  flutter_swiper_null_safety: ^1.0.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  google_mlkit_text_recognition: ^0.14.0
  image_cropper: ^8.1.0
  http: ^1.0.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
    - assets/icons/icono_app.png
    - assets/credit_card/visa_logo.png
    - assets/credit_card/creditcardchipsilver.png
    - assets/credit_card/card_band.jpg
    - assets/credit_card/card_back.jpg
    - assets/.env
    - data/initialData.json

  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icono_app.png"
  adaptive_icon_foreground: "assets/icons/icono_app.png"
  adaptive_icon_background: "#5F8F3C"
  remove_sdk_android: 21
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icono_app.png"

flutter_native_splash:
  color: "#f6f7d5"
  image: assets/icons/bankify.gif
  android: true
  ios: true
  web: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
