name: flutter_bank_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^1.1.6
  get_it: ^8.0.2
  go_router: ^14.6.2
  rive: ^0.9.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
    - assets/icons/icono_app.png

  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icono_app.png"
  adaptive_icon_foreground: "assets/icons/icono_app.png"
  adaptive_icon_background: "#5F8F3C"
  remove_sdk_android: 21
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icono_app.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/bankify.gif
  android: true
  ios: true
  web: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
